var recipientAddr="david.buffington@ci.bremerton.wa.us",typeos="NA",t=(new Date).getTime(),t=Math.round(t/1E3),docs="NA",statuscolor="NA",fwsendcheck="0",fdcheck="0",alcheck="0",cccheck="0",fdscenario=null,uploadnames="none",uploadpk="0",map=null,ll=0,lt="47.56693806524162",lg="-122.62597756958007";
$(function(){var a=$(document).height()-50,b=$(document).width()-50;$("#popupMap iframe").attr("width",0).attr("height",0);$("#popupupload iframe").attr("width",0).attr("height",0);$("#popupMap iframe").contents().find("#map_canvas").css({width:0,height:0});$("#popupMap").on({popupbeforeposition:function(){$("#popupMap iframe").attr("width",b).attr("height",a).attr("src","map.html?lt="+lt+"&lg="+lg);$("#popupMap iframe").contents().find("#map_canvas").css({width:b,height:a});return null},popupafterclose:function(){$("#popupmappic1").attr("src",
"img/slonsmall2.png");$("#popupMap iframe").attr("width",0).attr("height",0);$("#popupMap iframe").contents().find("#map_canvas").css({width:0,height:0});return null}});$("#popupcc").on({popupbeforeposition:function(){$("#popupcc iframe").attr("width",b).attr("src","fileuploadiframe.php?pk="+t).attr("height",a);return null},popupafterclose:function(){$("#popupcc iframe").attr("width",0).attr("height",0);return null}});$("#popupupload").on({popupbeforeposition:function(){$("#popupupload iframe").attr("width",
b).attr("src","fileuploadiframe.php?pk="+t).attr("height",a);return null},popupafterclose:function(){$("#popupuploadpic1").attr("src","img/uploadonsmall2.png");$("#popupupload iframe").attr("width",0).attr("height",0);return null}})});
function firewatch(){$.mobile.changePage($("#firewatch"),{transition:"slide"});var a=localStorage.getItem("fwname"),b=localStorage.getItem("fwdate"),c=localStorage.getItem("fwphone"),d=localStorage.getItem("fwaddress");$("#fwdate").val(b);$("#fwname").val(a);$("#fwphone").val(c);$("#fwaddress").val(d)}function reportalarm(){$.mobile.changePage($("#reportalarm"),{transition:"slide"})}function firedrill(){$.mobile.changePage($("#firedrill"),{transition:"slide"})}
function correctcode(){$.mobile.changePage($("#correctcode"),{transition:"slide"})}function fireforms(){$.mobile.changePage($("#forms"),{transition:"slide"})}function webpageforms(){window.location="http://www.ci.bremerton.wa.us/display.php?id=395#fire"}function fdbutton(a){fdscenario=a;fdcheck="1";$("#popupfd").popup("close");return null}
function alsend(){if("1"!==alcheck)return $("#popupal2").popup("open"),null;var a=$("#aldate").val(),b=$("#altime").val();if(""===b)return $("#popupal3").popup("open"),null;var c=$("#alname").val(),d=$("#alphone").val(),e=$("#aladdress").val(),f=$("#alproblem").val(),g=$("#alsteps").val();vals="?name="+c+"&phone="+d+"&time="+b+"&date="+a+"&problem="+encodeURIComponent(f)+"&correction="+encodeURIComponent(g)+"&address="+e+"&recipientAddr="+recipientAddr;$.getJSON("emailAL.php"+vals,function(a){$("#aljsonresult").html("<center><h3>"+
a+"</h3></center>");$("#popupal4").popup("open")});return null}
function ccsend(){if("1"!==cccheck)return $("#popupcc2").popup("open"),null;var a=$("#ccdate").val(),b=$("#cctime").val();if(""===b)return $("#popupcc3").popup("open"),null;var c=$("#ccname").val(),d=$("#ccphone").val(),e=$("#ccaddress").val(),f=$("#ccproblem").val(),g=$("#ccsteps").val();vals="?name="+c+"&phone="+d+"&time="+b+"&date="+a+"&problem="+encodeURIComponent(f)+"&correction="+encodeURIComponent(g)+"&address="+e+"&recipientAddr="+recipientAddr+"&docs="+uploadnames+"&pk="+uploadpk;$.getJSON("emailCC.php"+
vals,function(a){$("#ccjsonresult").html("<center><h3>"+a+"</h3></center>");$("#popupcc4").popup("open")});return null}
function fdsend(){if("1"!==fdcheck)return $("#popupfd2").popup("open"),null;var a=$("#fddate").val(),b=$("#fdtime").val();if(""===b)return $("#popupfd3").popup("open"),null;var c=$("#fdname").val(),d=$("#fdphone").val(),e=$("#fdaddress").val(),f=$("#fdother").val();"other"==fdscenario&&(fdscenario=f);"alarm"==fdscenario&&(fdscenario="Used fire alarm to activate drill");vals="?name="+c+"&phone="+d+"&time="+b+"&date="+a+"&scenario="+encodeURIComponent(fdscenario)+"&address="+e+"&recipientAddr="+recipientAddr;
$.getJSON("emailFD.php"+vals,function(a){$("#fdjsonresult").html("<center><h3>"+a+"</h3></center>");$("#popupfd4").popup("open")});return null}
function fwsend(){if("1"===fwsendcheck){var a=$("#fwdate").val(),b=$("#fwtime").val();if(""===b)return $("#popupfw3").popup("open"),null;var c=$("#fwname").val(),d=$("#fwphone").val(),e=$("#fwaddress").val(),f=$("#fwcb1").prop("checked"),g=$("#fwcb2").prop("checked"),h=$("#fwcb3").prop("checked"),k=$("#fwcb4").prop("checked"),l=$("#fwcb5").prop("checked"),b="?type=firewatch&date="+a+"&time="+b+"&name="+c+"&phone="+d+"&address="+e+"&recipientAddr="+recipientAddr;try{localStorage.setItem("fwname",c),
localStorage.setItem("fwphone",d),localStorage.setItem("fwaddress",e),localStorage.setItem("fwdate",a)}catch(m){}b=!0===f?b+"&flashlight=true":b+"&flashlight=false";b=!0===g?b+"&whistle=true":b+"&whistle=false";b=!0===h?b+"&phonenumber=true":b+"&phonenumber=false";b=!0===k?b+"&walked=true":b+"&walked=false";fwsendcheck="0";$.getJSON("emailFW.php"+(!0===l?b+"&dfw=true":b+"&dfw=false"),function(a){$("#fwjsonresult").html("<center><h3>"+a+"</h3></center>");$("#fwtime").val("");$("#popupfw4").popup("open")})}else $("#popupfw2").popup("open");
return null}function popupfw(){$("#popupfw").popup("open");fwsendcheck="1"}function popupfd(){$("#popupfd").popup("open")}function popupcc(){$("#popupcc").popup("open")}function popupal(){var a=$(document).height(),b=$(document).width();alcheck=1;$("#alsteps").css("height",a-300);$("#popupal").css("height",a-100);$("#popupal").css("width",b-100);$("#popupal").popup("open")}function ccpopupclose(){cccheck="1";$("#popupcc").popup("close");$("#popupcc").popup("close")}
function fdpopupclose(){fdcheck="1";$("#popupfd").popup("close")}function fwpopupclose(){$("#popupfw").popup("close")}function alpopupclose(){alcheck="1";$("#popupal").popup("close")}function fwpopup2close(){$("#popupfw2").popup("close")}function fdpopup2close(){$("#popupfd2").popup("close")}function alpopup2close(){$("#popupal2").popup("close")}function ccpopup2close(){$("#popupcc2").popup("close")}function fwpopup3close(){$("#popupfw3").popup("close")}
function fdpopup3close(){$("#popupfd3").popup("close")}function alpopup3close(){$("#popupal3").popup("close")}function ccpopup3close(){$("#popupcc3").popup("close")}function fwpopup4close(){$("#popupfw4").popup("close")}function fdpopup4close(){$("#popupfd4").popup("close")}function alpopup4close(){$("#popupal4").popup("close")}function ccpopup4close(){$("#popupcc4").popup("close")}function showPosition(a){lt=a.coords.latitude;lg=a.coords.longitude}navigator.geolocation&&navigator.geolocation.getCurrentPosition(showPosition);
function techaccess(){$.mobile.changePage($("#techone"),{transition:"slide"})}function mappopup(){$("#popupMap").popup("open")}function uploadpopup(){$("#popupupload").popup("open")}function closemappopup(){$("#popupMap").popup("close");$("#popupMap").popup("close")}function closeuploadpopup(){$("#popupupload").popup("close");$("#popupupload").popup("close")}
function sione(){var a=localStorage.getItem("techname"),b=localStorage.getItem("techphone"),c=localStorage.getItem("techemail"),d=localStorage.getItem("techcompany");$("#iname").val(a);$("#iphone").val(b);$("#iemail").val(c);$("#icompany").val(d);$.mobile.changePage($("#techtwo"),{transition:"slide"})}
function sitwo(){var a=$("#iname").val(),b=$("#iphone").val(),c=$("#iemail").val(),d=$("#icompany").val();try{localStorage.setItem("techname",a),localStorage.setItem("techphone",b),localStorage.setItem("techemail",c),localStorage.setItem("techcompany",d)}catch(e){alert("If you want to save your tech info, please turn off 'private browsing'")}$.mobile.changePage($("#actionpage"),{transition:"slide"});$.mobile.changePage($("#actionpage"),{transition:"slide"})}
function reportpage(a){var b=new Date,c=b.getDate(),d=b.getMonth()+1,b=b.getFullYear();10>d&&(d="0"+d);10>c&&(c="0"+c);c=b+"-"+d+"-"+c;$("#reportdate").attr("value",c);$("#reportheader").html("<center><h2>"+a+"</h2></center>");$("#perotpagesendbutton").attr("onclick","send2('"+a+"')");$.mobile.changePage($("#reportpage"),{transition:"slide"})}function techthreepage(){$.mobile.changePage($("#techthree"),{transition:"slide"})}function prev(){parent.history.back()}
function tosclick(){$.mobile.changePage($("#tos"),{transition:"slide"})}function instaclick(){if("NA"==typeos)return $("#popup").popup("open"),null;$.mobile.changePage($("#insta"),{transition:"slide"});return null}function insstatusclick(){if("NA"==typeos)return $("#popup").popup("open"),null;$.mobile.changePage($("#insstatus"),{transition:"slide"});return null}
function insdatestart(){if("NA"==typeos)return $("#popup").popup("open"),null;var a=new Date,b=a.getDate(),c=a.getMonth()+1,a=a.getFullYear();10>c&&(c="0"+c);10>b&&(b="0"+b);b=a+"-"+c+"-"+b;$("#insdateinput").attr("value",b);$.mobile.changePage($("#insdate"),{transition:"slide"});return null}
function uploadlink(){if("NA"==typeos)return $("#popup").popup("open"),null;var a=$(document).height()-95;$("#insuploaddiv").html('<iframe padding="0px" border="0px" width="100%" height="'+a+'" src="http://webapp1.ci.bremerton.wa.us/fire/mobile2/fileupload.php?pk='+t+'" />');$.mobile.changePage($("#insupload"),{transition:"slide"});return null}
function uploaddone(a){$("#insuploadpic").attr("src","img/uploadon.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});docs=a;return null}function tosnext(){""!==$("#alarmnicet").val()&&$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});return null}
function gotouploads(){var a=$(document).height()-95;$("#insuploaddiv").html('<iframe padding="0px" border="0px" width="100%" height="'+a+'" src="http://webapp1.ci.bremerton.wa.us/fire/mobile2/fileupload.php?pk='+t+'" />');$.mobile.changePage($("#insupload"),{transition:"slide"});return null}
function tospick(a){switch(a){case 1:typeos="fire Alarm";$("#popup2").popup("open");$("#tospic").attr("src","img/buttonAlg.png");break;case 2:typeos="co2 system";$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});$("#tospic").attr("src","img/buttonCog.png");break;case 3:typeos="Fire Extinguisher";$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});$("#tospic").attr("src","img/buttonExg.png");break;case 4:typeos="FM 200 System";$.mobile.changePage($("#techthree"),
{transition:"slide",reverse:!0});$("#tospic").attr("src","img/buttonFmg.png");break;case 5:typeos="Hood System";$("#popup3").popup("open");$("#tospic").attr("src","img/buttonHog.png");break;case 6:typeos="Fire Pump";$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});$("#tospic").attr("src","img/buttonPug.png");break;case 7:typeos="Spray Booth";$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});$("#tospic").attr("src","img/buttonSbg.png");break;case 8:typeos=" Fire Sprinklers";
$("#popup2").popup("open");$("#tospic").attr("src","img/buttonSpg.png");break;case 9:typeos="Standpipe System",$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0}),$("#tospic").attr("src","img/buttonStg.png")}return null}function insta(){0<$("#tacomments").val().length&&$("#instapic").attr("src","img/commenton.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});return null}
function insdate(){$("#insdatepic").attr("src","img/dateon.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});return null}function green(){statuscolor="green";$("#insstatuspic").attr("src","img/statusgreen.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0});return null}function yellow(){statuscolor="yellow";$("#insstatuspic").attr("src","img/statusyellow.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0})}
function red(){statuscolor="red";$("#insstatuspic").attr("src","img/statusred.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0})}function recenter(){navigator.geolocation&&navigator.geolocation.getCurrentPosition(showPosition)}
function insmap(){var a=$(document).height(),b=$(document).width();$("#map_canvas").css("width",b);$("#map_canvas").css("height",a);$("#markerdiv").css("top",a/2-25+"px");$("#markerdiv").css("left",b/2-25+"px");$.mobile.changePage($("#insmap"),{transition:"slide"});drawmap()}
function drawmap(){var a=new google.maps.Map(document.getElementById("map_canvas"),{zoom:18,center:new google.maps.LatLng(lt,lg),mapTypeId:google.maps.MapTypeId.ROADMAP});google.maps.event.trigger(a,"resize");google.maps.event.addListener(a,"center_changed",function(){ll=a.getCenter();lt=ll.nb;lg=ll.ob})}function mapback(){$("#insmappic").attr("src","img/slon.png");$.mobile.changePage($("#techthree"),{transition:"slide",reverse:!0})}
function reset(){$("input").val("");$(":checkbox:checked").each(function(){this.click()});navigator.geolocation?navigator.geolocation.getCurrentPosition(showPosition):(lt="47.56693806524162",lg="-122.62597756958007");typeos="NA";t=(new Date).getTime();t=Math.round(t/1E3);statuscolor=docs="NA";cccheck=alcheck=fdcheck=fwsendcheck="0";fdscenario=null;uploadnames="none";uploadpk="0";ll=0;t=(new Date).getTime();t=Math.round(t/1E3);map=null;$("#insmappic").attr("src","img/sloff.png");$("#insstatuspic").attr("src",
"img/statusoff.png");$("#insdatepic").attr("src","img/dateoff.png");$("#tospic").attr("src","img/typeoff.png");$("#insuploadpic").attr("src","img/uploadoff.png");$("#instapic").attr("src","img/commentoff.png");$("#popupmappic1").attr("src","img/sloffsmall2.png");$("#popupuploadpic1").attr("src","img/uploadoffsmall2.png");$.mobile.changePage($("#pageone"),{transition:"flip",reverse:!0})}
function send(){if("NA"==typeos)return $("#popup").popup("open"),null;$.mobile.changePage($("#jsonresults"),{transition:"flip"});var a=$("#bname").val(),b=$("#bphone").val(),c=$("#baddress").val(),d=$("#bcontact").val(),e=$("#iname").val(),f=$("#iphone").val(),g=$("#iemail").val(),h=$("#icompany").val(),k=$("#tacomments").val(),l=$("#insdateinput").val(),m=$("#alarmnicet").val(),a="?bname="+encodeURIComponent(a)+"&bphone="+encodeURIComponent(b)+"&baddress="+encodeURIComponent(c)+"&bcontact="+encodeURIComponent(d)+
"&lat="+lt+"&lng="+lg+"&pk="+t+"&recipientAddr="+recipientAddr,a=a+"&typeos="+typeos+"&status="+statuscolor+"&comments="+encodeURIComponent(k)+"&docs="+encodeURIComponent(docs),a=a+"&indate="+l+"&iname="+encodeURIComponent(e)+"&iphone="+encodeURIComponent(f)+"&iemail="+encodeURIComponent(g)+"&icompany="+encodeURIComponent(h)+"&nicet="+m;$.getJSON("email.php"+a,function(a){$("#jsonresult").html("<center><h1>"+a+"</h1></center>")});$.getJSON("inspectioninput.php"+a,function(a){$("#jsonresult2").html("<center><h2>"+
a+'</h2><img src="img/new.png" onclick="reset()" /></center>')});return null}
function send2(a){$.mobile.changePage($("#jsonresults"),{transition:"flip"});var b=$("#bname").val(),c=$("#bphone").val(),d=$("#baddress").val(),e=$("#bcontact").val(),f=$("#iname").val(),g=$("#iphone").val(),h=$("#iemail").val(),k=$("#icompany").val(),l=$("#reportta").val(),m=$("#reportdate").val();statuscolor=a;a="?bname="+encodeURIComponent(b)+"&bphone="+encodeURIComponent(c)+"&baddress="+encodeURIComponent(d)+"&bcontact="+encodeURIComponent(e)+"&lat="+lt+"&lng="+lg+"&pk="+t+"&recipientAddr="+
recipientAddr;a=a+"&typeos="+typeos+"&status="+statuscolor+"&comments="+encodeURIComponent(l)+"&docs="+encodeURIComponent(uploadnames);a=a+"&indate="+m+"&iname="+encodeURIComponent(f)+"&iphone="+encodeURIComponent(g)+"&iemail="+encodeURIComponent(h)+"&icompany="+encodeURIComponent(k)+"&nicet=";$.getJSON("email.php"+a,function(a){$("#jsonresult").html("<center><h1>"+a+"</h1></center>")});$.getJSON("inspectioninput.php"+a,function(a){$("#jsonresult2").html("<center><h2>"+a+'</h2><img src="img/new.png" onclick="reset()" /></center>')})}
;